language: python
dist: xenial
cache: pip

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8-dev
      env: TOXENV=py38dev
    - python: 3.6
      env: TOXENV=style
    - python: 3.6
      env: TOX_ENV=cover

script: tox -e $TOX_ENV

install: pip install --upgrade tox

after_success: pip install coveralls && coveralls
