language: python
dist: xenial
cache: pip

matrix:
  include:
    - python: 3.6
      env: TOX_ENV=py36
    - python: 3.7
      env: TOX_ENV=py37
    - python: 3.8-dev
      env: TOX_ENV=py38dev
    - python: 3.6
      env: TOX_ENV=style
  allow_failures:
    - python: 3.6
      env: TOX_ENV=coveralls
  fast_finish: true

script: tox -e $TOX_ENV

install: pip install --upgrade tox
